apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2021-08-07T23:32:24Z"
    generation: 1
    labels:
      app: hello-world-java
    name: hello-world-java
    namespace: default
    resourceVersion: "2231558"
    uid: fbda98b3-5696-4474-b69a-85e9af54c1e1
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: hello-world-java
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hello-world-java
      spec:
        containers:
        - image: harshareddy319/hello-world-java:0.0.1.release
          imagePullPolicy: IfNotPresent
          name: hello-world-java
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2021-08-07T23:32:24Z"
      lastUpdateTime: "2021-08-07T23:32:24Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2021-08-13T02:46:31Z"
      lastUpdateTime: "2021-08-13T02:46:31Z"
      message: ReplicaSet "hello-world-java-568d75d969" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: "False"
      type: Progressing
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2021-08-07T23:24:48Z"
    generation: 1
    labels:
      app: hello-world-nodejs
    name: hello-world-nodejs
    namespace: default
    resourceVersion: "2231635"
    uid: 03c3acb8-8620-448c-be39-98f696bf2166
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: hello-world-nodejs
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hello-world-nodejs
      spec:
        containers:
        - image: harshareddy319/hello-world-nodejs:1.0.0.release
          imagePullPolicy: IfNotPresent
          name: hello-world-nodejs
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2021-08-07T23:24:48Z"
      lastUpdateTime: "2021-08-07T23:24:48Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2021-08-13T02:46:47Z"
      lastUpdateTime: "2021-08-13T02:46:47Z"
      message: ReplicaSet "hello-world-nodejs-5998f998fd" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: "False"
      type: Progressing
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
